export {default as Brands } from "./Brands";
export {default as Buy } from "./Buy";
export {default as CTA } from "./CTA";
export {default as Footer } from "./Footer";
export {default as Header } from "./Header";
export {default as Hero } from "./Hero";
export {default as StartDoc } from "./StartDoc";
export {default as Testimonials } from "./Testimonials";
export {default as Youneed } from "./Youneed";